### ISSUE TITLE
ImportError: cannot import name 'SubstrateRequestException' from 'substrateinterface'

### ISSUE THREAD

**Issue by andybut** [starkleytech/substrate-faucet#1]
Hello. I am trying to run a program and I get an ImportError: cannot import name 'SubstrateRequestException' from 'substrateinterface' error. Please tell me what could be the reason? Are there any additional requirements for the environment? I would be grateful for your answer.

**Comment by masterdubs** [comment]
Which version of python are you using ?

**Comment by masterdubs** [comment]
fixed by commit 5b84bc3ced53f046d6971c1e5266c863bc7b0d4e
